services:
    app:
        build:
            context: docker
            dockerfile: Dockerfile
        #    image: laravel-app
        container_name: content-hub-app
        volumes:
            - .:/var/www
        depends_on:
            - db
        networks:
            - content-hub

    db:
        image: postgres:15
        container_name: content-hub-db
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - "5436:${DB_PORT}"
        volumes:
            - content-hub:/var/lib/postgresql/data
        networks:
            - content-hub

    nginx:
        image: nginx:alpine
        container_name: content-hub-nginx
        ports:
            - "90:80"
        volumes:
            - .:/var/www
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - content-hub

    node:
        image: node:20-alpine
        container_name: content-hub-node
        working_dir: /var/www
        volumes:
            - .:/var/www
            - /var/www/node_modules  # node_modules ni konteyner ichida saqlash (hostda emas)
        ports:
            - "5173:5173"
        networks:
            - content-hub
        command: sh -c "npm install && npm run dev"



volumes:
    content-hub:

networks:
    content-hub:
